///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RivianR1Configurator.RivianConfigurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddAccessory recording.
    /// </summary>
    [TestModule("6305587a-8763-4c70-adea-1feb519fc919", ModuleType.Recording, 1)]
    public partial class AddAccessory : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RivianR1Configurator.RivianR1ConfiguratorRepository repository.
        /// </summary>
        public static global::RivianR1Configurator.RivianR1ConfiguratorRepository repo = global::RivianR1Configurator.RivianR1ConfiguratorRepository.Instance;

        static AddAccessory instance = new AddAccessory();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddAccessory()
        {
            OptionCost = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddAccessory Instance
        {
            get { return instance; }
        }

#region Variables

        string _OptionCost;

        /// <summary>
        /// Gets or sets the value of variable OptionCost.
        /// </summary>
        [TestVariable("f5cee37d-13d2-4aef-b96a-3a10567980fa")]
        public string OptionCost
        {
            get { return _OptionCost; }
            set { _OptionCost = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable OptionName.
        /// </summary>
        [TestVariable("8a747431-c949-46ee-95f6-b0abdd141d6b")]
        public string OptionName
        {
            get { return repo.OptionName; }
            set { repo.OptionName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'RivianElectricAdventureVehicles.AddRemove'.", repo.RivianElectricAdventureVehicles.AddRemoveInfo, new RecordItemIndex(0));
            repo.RivianElectricAdventureVehicles.AddRemove.Press();
            Delay.Milliseconds(0);
            
            VehiclePriceCalculator.AddOptionCost(OptionCost);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
