///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RivianR1Configurator.RivianConfigurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddInteriorColorAndNavigation recording.
    /// </summary>
    [TestModule("6fe0aefc-c0a9-4320-9380-618eefe2ee54", ModuleType.Recording, 1)]
    public partial class AddInteriorColorAndNavigation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RivianR1Configurator.RivianR1ConfiguratorRepository repository.
        /// </summary>
        public static global::RivianR1Configurator.RivianR1ConfiguratorRepository repo = global::RivianR1Configurator.RivianR1ConfiguratorRepository.Instance;

        static AddInteriorColorAndNavigation instance = new AddInteriorColorAndNavigation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddInteriorColorAndNavigation()
        {
            InteriorCost = "3000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddInteriorColorAndNavigation Instance
        {
            get { return instance; }
        }

#region Variables

        string _InteriorCost;

        /// <summary>
        /// Gets or sets the value of variable InteriorCost.
        /// </summary>
        [TestVariable("d468a89b-9620-4cbd-a984-8e22f81a231c")]
        public string InteriorCost
        {
            get { return _InteriorCost; }
            set { _InteriorCost = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable InteriorColor.
        /// </summary>
        [TestVariable("a21c8d5f-bd6b-4293-a289-346afbea0dc3")]
        public string InteriorColor
        {
            get { return repo.InteriorColor; }
            set { repo.InteriorColor = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'RivianElectricAdventureVehicles.InteriorColor'.", repo.RivianElectricAdventureVehicles.InteriorColorInfo, new RecordItemIndex(0));
            repo.RivianElectricAdventureVehicles.InteriorColor.As<Button>().Press();
            Delay.Milliseconds(0);
            
            // Removed Option Cost Here
            Report.Log(ReportLevel.Info, "Section", "Removed Option Cost Here", new RecordItemIndex(1));
            
            //Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'RivianElectricAdventureVehicles.Next'.", repo.RivianElectricAdventureVehicles.NextInfo, new RecordItemIndex(2));
            //repo.RivianElectricAdventureVehicles.Next.As<Button>().Press();
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
