///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RivianR1Configurator.RivianConfigurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfigurePanel1R1T recording.
    /// </summary>
    [TestModule("61388b9f-a6a3-4ccb-b64c-a041e7cb4632", ModuleType.Recording, 1)]
    public partial class ConfigurePanel1R1T : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RivianR1Configurator.RivianR1ConfiguratorRepository repository.
        /// </summary>
        public static global::RivianR1Configurator.RivianR1ConfiguratorRepository repo = global::RivianR1Configurator.RivianR1ConfiguratorRepository.Instance;

        static ConfigurePanel1R1T instance = new ConfigurePanel1R1T();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfigurePanel1R1T()
        {
            AllTerrainCost = "4950";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfigurePanel1R1T Instance
        {
            get { return instance; }
        }

#region Variables

        string _AllTerrainCost;

        /// <summary>
        /// Gets or sets the value of variable AllTerrainCost.
        /// </summary>
        [TestVariable("94d53d52-aeba-489f-ab01-6c644ff6f529")]
        public string AllTerrainCost
        {
            get { return _AllTerrainCost; }
            set { _AllTerrainCost = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'RivianElectricAdventureVehicles.AllTerrainAddRemoveButton'.", repo.RivianElectricAdventureVehicles.AllTerrainAddRemoveButtonInfo, new RecordItemIndex(0));
            repo.RivianElectricAdventureVehicles.AllTerrainAddRemoveButton.Press();
            Delay.Milliseconds(0);
            
            VehiclePriceCalculator.AddOptionCost(AllTerrainCost);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
