///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RivianR1Configurator.RivianConfigurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfigurePaint recording.
    /// </summary>
    [TestModule("ada65727-0a8c-495e-9934-a0193b4b3f79", ModuleType.Recording, 1)]
    public partial class ConfigurePaint : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RivianR1Configurator.RivianR1ConfiguratorRepository repository.
        /// </summary>
        public static global::RivianR1Configurator.RivianR1ConfiguratorRepository repo = global::RivianR1Configurator.RivianR1ConfiguratorRepository.Instance;

        static ConfigurePaint instance = new ConfigurePaint();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfigurePaint()
        {
            PaintCost = "3000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfigurePaint Instance
        {
            get { return instance; }
        }

#region Variables

        string _PaintCost;

        /// <summary>
        /// Gets or sets the value of variable PaintCost.
        /// </summary>
        [TestVariable("6862f92d-2208-4ff2-aa8d-1b9f6ec04b57")]
        public string PaintCost
        {
            get { return _PaintCost; }
            set { _PaintCost = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PaintColor.
        /// </summary>
        [TestVariable("66f46c2d-526d-4b05-a705-16aad5d61845")]
        public string PaintColor
        {
            get { return repo.PaintColor; }
            set { repo.PaintColor = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'RivianElectricAdventureVehicles.ExteriorPaintColor'.", repo.RivianElectricAdventureVehicles.ExteriorPaintColorInfo, new RecordItemIndex(0));
            repo.RivianElectricAdventureVehicles.ExteriorPaintColor.As<Button>().Press();
            Delay.Milliseconds(0);
            
            VehiclePriceCalculator.AddOptionCost(PaintCost);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
