///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RivianR1Configurator.RivianConfigurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RivianNavigation recording.
    /// </summary>
    [TestModule("0fd5966d-89e1-427a-a6b4-86e5a75987aa", ModuleType.Recording, 1)]
    public partial class RivianNavigation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RivianR1Configurator.RivianR1ConfiguratorRepository repository.
        /// </summary>
        public static global::RivianR1Configurator.RivianR1ConfiguratorRepository repo = global::RivianR1Configurator.RivianR1ConfiguratorRepository.Instance;

        static RivianNavigation instance = new RivianNavigation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RivianNavigation()
        {
            Model = "R1S";
            basePrice = "105900";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RivianNavigation Instance
        {
            get { return instance; }
        }

#region Variables

        string _basePrice;

        /// <summary>
        /// Gets or sets the value of variable basePrice.
        /// </summary>
        [TestVariable("2f11bda2-f301-4a2e-a466-801c74785758")]
        public string basePrice
        {
            get { return _basePrice; }
            set { _basePrice = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable Model.
        /// </summary>
        [TestVariable("d187caf3-feae-430b-ba65-261566ced36e")]
        public string Model
        {
            get { return repo.Model; }
            set { repo.Model = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable TrimLevel.
        /// </summary>
        [TestVariable("4a262ae0-e29c-49a1-9780-a3ffa7b110b5")]
        public string TrimLevel
        {
            get { return repo.TrimLevel; }
            set { repo.TrimLevel = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse None Move item 'RivianElectricAdventureVehicles.ModelNavSelector' at Center.", repo.RivianElectricAdventureVehicles.ModelNavSelectorInfo, new RecordItemIndex(0));
            repo.RivianElectricAdventureVehicles.ModelNavSelector.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'RivianElectricAdventureVehicles.BuyMenu'.", repo.RivianElectricAdventureVehicles.BuyMenuInfo, new RecordItemIndex(1));
            repo.RivianElectricAdventureVehicles.BuyMenu.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'RivianElectricAdventureVehicles.BuildButton'.", repo.RivianElectricAdventureVehicles.BuildButtonInfo, new RecordItemIndex(2));
            repo.RivianElectricAdventureVehicles.BuildButton.PerformClick();
            Delay.Milliseconds(0);
            
            VehiclePriceCalculator.InitializeBasePrice(basePrice);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
