///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RivianR1Configurator.RivianConfigurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartRivianWebTest recording.
    /// </summary>
    [TestModule("54b9bdb8-b602-4c26-bdce-8112eff64016", ModuleType.Recording, 1)]
    public partial class StartRivianWebTest : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RivianR1Configurator.RivianR1ConfiguratorRepository repository.
        /// </summary>
        public static global::RivianR1Configurator.RivianR1ConfiguratorRepository repo = global::RivianR1Configurator.RivianR1ConfiguratorRepository.Instance;

        static StartRivianWebTest instance = new StartRivianWebTest();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartRivianWebTest()
        {
            Incognito = "False";
            Browser = "Chrome";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartRivianWebTest Instance
        {
            get { return instance; }
        }

#region Variables

        string _Incognito;

        /// <summary>
        /// Gets or sets the value of variable Incognito.
        /// </summary>
        [TestVariable("b92b43b3-c33c-453b-aaf0-4085e86c5594")]
        public string Incognito
        {
            get { return _Incognito; }
            set { _Incognito = value; }
        }

        string _Browser;

        /// <summary>
        /// Gets or sets the value of variable Browser.
        /// </summary>
        [TestVariable("ee5f10ac-5b6b-4032-a02a-a4ca4504679a")]
        public string Browser
        {
            get { return _Browser; }
            set { _Browser = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://www.rivian.com' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://www.rivian.com", Browser, "", false, false, false, false, false, Boolean.Parse(Incognito), false, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
