///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RivianR1Configurator.RivianConfigurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateFinalPriceR1T recording.
    /// </summary>
    [TestModule("fbe4c908-84f2-4039-aa62-f603f9a85aeb", ModuleType.Recording, 1)]
    public partial class ValidateFinalPriceR1T : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RivianR1Configurator.RivianR1ConfiguratorRepository repository.
        /// </summary>
        public static global::RivianR1Configurator.RivianR1ConfiguratorRepository repo = global::RivianR1Configurator.RivianR1ConfiguratorRepository.Instance;

        static ValidateFinalPriceR1T instance = new ValidateFinalPriceR1T();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateFinalPriceR1T()
        {
            TotalVehiclePrice = "";
            GlobalTotalVehiclePrice = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateFinalPriceR1T Instance
        {
            get { return instance; }
        }

#region Variables

        string _TotalVehiclePrice;

        /// <summary>
        /// Gets or sets the value of variable TotalVehiclePrice.
        /// </summary>
        [TestVariable("533699d1-47c2-44c5-b2ba-9e829f55bfea")]
        public string TotalVehiclePrice
        {
            get { return _TotalVehiclePrice; }
            set { _TotalVehiclePrice = value; }
        }

        string _GlobalTotalVehiclePrice;

        /// <summary>
        /// Gets or sets the value of variable GlobalTotalVehiclePrice.
        /// </summary>
        [TestVariable("1620ff67-38d9-4ed1-a90f-7c7c84eb74d6")]
        public string GlobalTotalVehiclePrice
        {
            get { return _GlobalTotalVehiclePrice; }
            set { _GlobalTotalVehiclePrice = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'RivianElectricAdventureVehicles.VehiclePrice'.", repo.RivianElectricAdventureVehicles.VehiclePriceInfo, new RecordItemIndex(0));
            repo.RivianElectricAdventureVehicles.VehiclePrice.PerformClick();
            Delay.Milliseconds(0);
            
            GlobalTotalVehiclePrice = VehiclePriceCalculator.ConvertToCurrencyFormattedString(GlobalTotalVehiclePrice);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$GlobalTotalVehiclePrice) on item 'RivianElectricAdventureVehicles.OrderPrice'.", repo.RivianElectricAdventureVehicles.OrderPriceInfo, new RecordItemIndex(2));
            Validate.AttributeEqual(repo.RivianElectricAdventureVehicles.OrderPriceInfo, "InnerText", GlobalTotalVehiclePrice);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (InnerText>'Checkout') on item 'RivianElectricAdventureVehicles.CheckoutButton'.", repo.RivianElectricAdventureVehicles.CheckoutButtonInfo, new RecordItemIndex(3));
            Validate.AttributeContains(repo.RivianElectricAdventureVehicles.CheckoutButtonInfo, "InnerText", "Checkout");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
