///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RivianR1Configurator.RivianConfigurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateFinalPriceR1S recording.
    /// </summary>
    [TestModule("99ea1de2-553b-4a65-956a-09e3f7f94ed3", ModuleType.Recording, 1)]
    public partial class ValidateFinalPriceR1S : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RivianR1Configurator.RivianR1ConfiguratorRepository repository.
        /// </summary>
        public static global::RivianR1Configurator.RivianR1ConfiguratorRepository repo = global::RivianR1Configurator.RivianR1ConfiguratorRepository.Instance;

        static ValidateFinalPriceR1S instance = new ValidateFinalPriceR1S();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateFinalPriceR1S()
        {
            TotalVehiclePrice = "";
            GlobalTotalVehiclePrice = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateFinalPriceR1S Instance
        {
            get { return instance; }
        }

#region Variables

        string _TotalVehiclePrice;

        /// <summary>
        /// Gets or sets the value of variable TotalVehiclePrice.
        /// </summary>
        [TestVariable("02f62ede-7ef9-49f6-a38c-c85b8b63b8de")]
        public string TotalVehiclePrice
        {
            get { return _TotalVehiclePrice; }
            set { _TotalVehiclePrice = value; }
        }

        string _GlobalTotalVehiclePrice;

        /// <summary>
        /// Gets or sets the value of variable GlobalTotalVehiclePrice.
        /// </summary>
        [TestVariable("77ab62e8-8b81-4960-942e-07268d503d60")]
        public string GlobalTotalVehiclePrice
        {
            get { return _GlobalTotalVehiclePrice; }
            set { _GlobalTotalVehiclePrice = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RivianElectricAdventureVehicles.VehiclePrice' at Center.", repo.RivianElectricAdventureVehicles.VehiclePriceInfo, new RecordItemIndex(0));
            //repo.RivianElectricAdventureVehicles.VehiclePrice.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'RivianElectricAdventureVehicles.VehiclePrice'.", repo.RivianElectricAdventureVehicles.VehiclePriceInfo, new RecordItemIndex(1));
            repo.RivianElectricAdventureVehicles.VehiclePrice.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'RivianElectricAdventureVehicles.VehiclePrice' and assigning its value to variable 'TotalVehiclePrice'.", repo.RivianElectricAdventureVehicles.VehiclePriceInfo, new RecordItemIndex(2));
            TotalVehiclePrice = repo.RivianElectricAdventureVehicles.VehiclePrice.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", TotalVehiclePrice, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "User", GlobalTotalVehiclePrice, new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='$116,600') on item 'RivianElectricAdventureVehicles.VehiclePrice'.", repo.RivianElectricAdventureVehicles.VehiclePriceInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.RivianElectricAdventureVehicles.VehiclePriceInfo, "InnerText", "$116,600");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='$3,000') on item 'RivianElectricAdventureVehicles.AccessoryPrice'.", repo.RivianElectricAdventureVehicles.AccessoryPriceInfo, new RecordItemIndex(6));
            Validate.AttributeEqual(repo.RivianElectricAdventureVehicles.AccessoryPriceInfo, "InnerText", "$3,000");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='$119,600') on item 'RivianElectricAdventureVehicles.OrderPrice'.", repo.RivianElectricAdventureVehicles.OrderPriceInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.RivianElectricAdventureVehicles.OrderPriceInfo, "InnerText", "$119,600");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Checkout - $1,000 deposit') on item 'RivianElectricAdventureVehicles.CheckoutButton'.", repo.RivianElectricAdventureVehicles.CheckoutButtonInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.RivianElectricAdventureVehicles.CheckoutButtonInfo, "InnerText", "Checkout - $1,000 deposit");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
