///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RivianR1Configurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RivianR1ConfiguratorRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("53401a27-61a6-4676-9daf-cf5b623150c2")]
    public partial class RivianR1ConfiguratorRepository : RepoGenBaseFolder
    {
        static RivianR1ConfiguratorRepository instance = new RivianR1ConfiguratorRepository();
        RivianR1ConfiguratorRepositoryFolders.RivianElectricAdventureVehiclesAppFolder _rivianelectricadventurevehicles;

        /// <summary>
        /// Gets the singleton class instance representing the RivianR1ConfiguratorRepository element repository.
        /// </summary>
        [RepositoryFolder("53401a27-61a6-4676-9daf-cf5b623150c2")]
        public static RivianR1ConfiguratorRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RivianR1ConfiguratorRepository() 
            : base("RivianR1ConfiguratorRepository", "/", null, 0, false, "53401a27-61a6-4676-9daf-cf5b623150c2", ".\\RepositoryImages\\RivianR1ConfiguratorRepository53401a27.rximgres")
        {
            _rivianelectricadventurevehicles = new RivianR1ConfiguratorRepositoryFolders.RivianElectricAdventureVehiclesAppFolder(this);
        }

#region Variables

        string _Department = "Management";

        /// <summary>
        /// Gets or sets the value of variable Department.
        /// </summary>
        [TestVariable("583e693d-15d4-47af-b698-6b6d471e094c")]
        public string Department
        {
            get { return _Department; }
            set { _Department = value; }
        }

        string _Gender = "Male";

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("9fa23028-d0c8-44c2-9574-1bbe573dc86b")]
        public string Gender
        {
            get { return _Gender; }
            set { _Gender = value; }
        }

        string _OptionName = "All-Terrain Package";

        /// <summary>
        /// Gets or sets the value of variable OptionName.
        /// </summary>
        [TestVariable("8a747431-c949-46ee-95f6-b0abdd141d6b")]
        public string OptionName
        {
            get { return _OptionName; }
            set { _OptionName = value; }
        }

        string _PaintColor = "Storm Blue";

        /// <summary>
        /// Gets or sets the value of variable PaintColor.
        /// </summary>
        [TestVariable("66f46c2d-526d-4b05-a705-16aad5d61845")]
        public string PaintColor
        {
            get { return _PaintColor; }
            set { _PaintColor = value; }
        }

        string _InteriorColor = "Slate Sky + Walnut Wood";

        /// <summary>
        /// Gets or sets the value of variable InteriorColor.
        /// </summary>
        [TestVariable("a21c8d5f-bd6b-4293-a289-346afbea0dc3")]
        public string InteriorColor
        {
            get { return _InteriorColor; }
            set { _InteriorColor = value; }
        }

        string _Model = "R1S";

        /// <summary>
        /// Gets or sets the value of variable Model.
        /// </summary>
        [TestVariable("4dfa59b9-c6f6-4c54-8bd8-d5f325155cf2")]
        public string Model
        {
            get { return _Model; }
            set { _Model = value; }
        }

        string _TrimLevel = "R1S Tri";

        /// <summary>
        /// Gets or sets the value of variable TrimLevel.
        /// </summary>
        [TestVariable("4a262ae0-e29c-49a1-9780-a3ffa7b110b5")]
        public string TrimLevel
        {
            get { return _TrimLevel; }
            set { _TrimLevel = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("53401a27-61a6-4676-9daf-cf5b623150c2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RivianElectricAdventureVehicles folder.
        /// </summary>
        [RepositoryFolder("228f874c-4af4-42d7-aee2-5836c61e504f")]
        public virtual RivianR1ConfiguratorRepositoryFolders.RivianElectricAdventureVehiclesAppFolder RivianElectricAdventureVehicles
        {
            get { return _rivianelectricadventurevehicles; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RivianR1ConfiguratorRepositoryFolders
    {
        /// <summary>
        /// The RivianElectricAdventureVehiclesAppFolder folder.
        /// </summary>
        [RepositoryFolder("228f874c-4af4-42d7-aee2-5836c61e504f")]
        public partial class RivianElectricAdventureVehiclesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rejectallInfo;
            RepoItemInfo _modelnavselectorInfo;
            RepoItemInfo _buymenuInfo;
            RepoItemInfo _buildbuttonInfo;
            RepoItemInfo _exteriorpaintcolorInfo;
            RepoItemInfo _interiorcolorInfo;
            RepoItemInfo _nextInfo;
            RepoItemInfo _addremoveInfo;
            RepoItemInfo _allterrainaddremovebuttonInfo;
            RepoItemInfo _vehiclepriceInfo;
            RepoItemInfo _accessorypriceInfo;
            RepoItemInfo _orderpriceInfo;
            RepoItemInfo _checkoutbuttonInfo;

            /// <summary>
            /// Creates a new RivianElectricAdventureVehicles  folder.
            /// </summary>
            public RivianElectricAdventureVehiclesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RivianElectricAdventureVehicles", "/dom[@domain='rivian.com']", parentFolder, 10000, null, false, "228f874c-4af4-42d7-aee2-5836c61e504f", "")
            {
                _rejectallInfo = new RepoItemInfo(this, "RejectAll", ".//div[#'ketch-consent-banner']//button[@innertext='Reject All']", "", 2000, null, "ba7926b1-6788-4604-ba2e-4548b6046d6a");
                _modelnavselectorInfo = new RepoItemInfo(this, "ModelNavSelector", ".//header[#'global-nav-bar']/nav//p[@innertext=$Model]", "", 30000, null, "1bfbf34e-9d9e-4584-9053-7115286b3221");
                _buymenuInfo = new RepoItemInfo(this, "BuyMenu", ".//header[#'global-nav-bar']/nav//p[@innertext='Buy']", "", 30000, null, "b851a1e1-74dd-4f95-b256-9e97b3438269");
                _buildbuttonInfo = new RepoItemInfo(this, "BuildButton", ".//div[#'compare-section']//p[@innertext=$TrimLevel]/..//a[@innertext='Build']", "", 30000, null, "2102cb42-b2e1-4d0a-a46d-35c731766fc6");
                _exteriorpaintcolorInfo = new RepoItemInfo(this, "ExteriorPaintColor", ".//button[@text=$PaintColor]", "", 30000, null, "b1524cfb-a238-4b89-80fa-d0a1bd541ff9");
                _interiorcolorInfo = new RepoItemInfo(this, "InteriorColor", ".//button[@text=$InteriorColor]", "", 30000, null, "6b810098-2374-4664-bf8c-58c2b7952947");
                _nextInfo = new RepoItemInfo(this, "Next", ".//button[@innertext>'Next']", "", 30000, null, "2dfc5107-1817-49f0-b9e3-751aa66f0b8a");
                _addremoveInfo = new RepoItemInfo(this, "AddRemove", ".//h4tag[@innertext=$OptionName]/ancestor::article//button/span[@innertext='Add']/ancestor::button", "", 30000, null, "a9f61703-e800-472e-a985-2d1adb61dc8a");
                _allterrainaddremovebuttonInfo = new RepoItemInfo(this, "AllTerrainAddRemoveButton", ".//h4tag[@innertext='All-Terrain Package']/ancestor::article//button/span[@innertext='Add']/ancestor::button", "", 30000, null, "972057df-0a41-4153-8994-e025c4353464");
                _vehiclepriceInfo = new RepoItemInfo(this, "VehiclePrice", "body//span[@innertext='Vehicle price']/ancestor::div[@class~'MuiButtonBase-root']/div[@class~'MuiAccordionSummary-expandIconWrapper']/span", "", 30000, null, "7d5a2672-25cb-4c7f-a3a1-518ff5d1f8fd");
                _accessorypriceInfo = new RepoItemInfo(this, "AccessoryPrice", "body//span[@innertext='Accessories']/../../..//span[@innertext>'$']", "", 30000, null, "79e8110f-5b82-435a-97f1-eaacb3c51c27");
                _orderpriceInfo = new RepoItemInfo(this, "OrderPrice", ".//div[@innertext='Order price']/following-sibling::span", "", 30000, null, "5b8fac29-72de-4b6a-b2c3-4b86768c13ec");
                _checkoutbuttonInfo = new RepoItemInfo(this, "CheckoutButton", ".//button[@innertext>'Checkout']", "", 30000, null, "060068ee-4d52-4fed-9143-38653e3a2e6d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("228f874c-4af4-42d7-aee2-5836c61e504f")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("228f874c-4af4-42d7-aee2-5836c61e504f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RejectAll item.
            /// </summary>
            [RepositoryItem("ba7926b1-6788-4604-ba2e-4548b6046d6a")]
            public virtual Ranorex.ButtonTag RejectAll
            {
                get
                {
                    return _rejectallInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The RejectAll item info.
            /// </summary>
            [RepositoryItemInfo("ba7926b1-6788-4604-ba2e-4548b6046d6a")]
            public virtual RepoItemInfo RejectAllInfo
            {
                get
                {
                    return _rejectallInfo;
                }
            }

            /// <summary>
            /// The ModelNavSelector item.
            /// </summary>
            [RepositoryItem("1bfbf34e-9d9e-4584-9053-7115286b3221")]
            public virtual Ranorex.PTag ModelNavSelector
            {
                get
                {
                    return _modelnavselectorInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The ModelNavSelector item info.
            /// </summary>
            [RepositoryItemInfo("1bfbf34e-9d9e-4584-9053-7115286b3221")]
            public virtual RepoItemInfo ModelNavSelectorInfo
            {
                get
                {
                    return _modelnavselectorInfo;
                }
            }

            /// <summary>
            /// The BuyMenu item.
            /// </summary>
            [RepositoryItem("b851a1e1-74dd-4f95-b256-9e97b3438269")]
            public virtual Ranorex.PTag BuyMenu
            {
                get
                {
                    return _buymenuInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The BuyMenu item info.
            /// </summary>
            [RepositoryItemInfo("b851a1e1-74dd-4f95-b256-9e97b3438269")]
            public virtual RepoItemInfo BuyMenuInfo
            {
                get
                {
                    return _buymenuInfo;
                }
            }

            /// <summary>
            /// The BuildButton item.
            /// </summary>
            [RepositoryItem("2102cb42-b2e1-4d0a-a46d-35c731766fc6")]
            public virtual Ranorex.ATag BuildButton
            {
                get
                {
                    return _buildbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BuildButton item info.
            /// </summary>
            [RepositoryItemInfo("2102cb42-b2e1-4d0a-a46d-35c731766fc6")]
            public virtual RepoItemInfo BuildButtonInfo
            {
                get
                {
                    return _buildbuttonInfo;
                }
            }

            /// <summary>
            /// The ExteriorPaintColor item.
            /// </summary>
            [RepositoryItem("b1524cfb-a238-4b89-80fa-d0a1bd541ff9")]
            public virtual Ranorex.ButtonTag ExteriorPaintColor
            {
                get
                {
                    return _exteriorpaintcolorInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ExteriorPaintColor item info.
            /// </summary>
            [RepositoryItemInfo("b1524cfb-a238-4b89-80fa-d0a1bd541ff9")]
            public virtual RepoItemInfo ExteriorPaintColorInfo
            {
                get
                {
                    return _exteriorpaintcolorInfo;
                }
            }

            /// <summary>
            /// The InteriorColor item.
            /// </summary>
            [RepositoryItem("6b810098-2374-4664-bf8c-58c2b7952947")]
            public virtual Ranorex.ButtonTag InteriorColor
            {
                get
                {
                    return _interiorcolorInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The InteriorColor item info.
            /// </summary>
            [RepositoryItemInfo("6b810098-2374-4664-bf8c-58c2b7952947")]
            public virtual RepoItemInfo InteriorColorInfo
            {
                get
                {
                    return _interiorcolorInfo;
                }
            }

            /// <summary>
            /// The Next item.
            /// </summary>
            [RepositoryItem("2dfc5107-1817-49f0-b9e3-751aa66f0b8a")]
            public virtual Ranorex.ButtonTag Next
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Next item info.
            /// </summary>
            [RepositoryItemInfo("2dfc5107-1817-49f0-b9e3-751aa66f0b8a")]
            public virtual RepoItemInfo NextInfo
            {
                get
                {
                    return _nextInfo;
                }
            }

            /// <summary>
            /// The AddRemove item.
            /// </summary>
            [RepositoryItem("a9f61703-e800-472e-a985-2d1adb61dc8a")]
            public virtual Ranorex.Button AddRemove
            {
                get
                {
                    return _addremoveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddRemove item info.
            /// </summary>
            [RepositoryItemInfo("a9f61703-e800-472e-a985-2d1adb61dc8a")]
            public virtual RepoItemInfo AddRemoveInfo
            {
                get
                {
                    return _addremoveInfo;
                }
            }

            /// <summary>
            /// The AllTerrainAddRemoveButton item.
            /// </summary>
            [RepositoryItem("972057df-0a41-4153-8994-e025c4353464")]
            public virtual Ranorex.Button AllTerrainAddRemoveButton
            {
                get
                {
                    return _allterrainaddremovebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AllTerrainAddRemoveButton item info.
            /// </summary>
            [RepositoryItemInfo("972057df-0a41-4153-8994-e025c4353464")]
            public virtual RepoItemInfo AllTerrainAddRemoveButtonInfo
            {
                get
                {
                    return _allterrainaddremovebuttonInfo;
                }
            }

            /// <summary>
            /// The VehiclePrice item.
            /// </summary>
            [RepositoryItem("7d5a2672-25cb-4c7f-a3a1-518ff5d1f8fd")]
            public virtual Ranorex.SpanTag VehiclePrice
            {
                get
                {
                    return _vehiclepriceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The VehiclePrice item info.
            /// </summary>
            [RepositoryItemInfo("7d5a2672-25cb-4c7f-a3a1-518ff5d1f8fd")]
            public virtual RepoItemInfo VehiclePriceInfo
            {
                get
                {
                    return _vehiclepriceInfo;
                }
            }

            /// <summary>
            /// The AccessoryPrice item.
            /// </summary>
            [RepositoryItem("79e8110f-5b82-435a-97f1-eaacb3c51c27")]
            public virtual Ranorex.SpanTag AccessoryPrice
            {
                get
                {
                    return _accessorypriceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The AccessoryPrice item info.
            /// </summary>
            [RepositoryItemInfo("79e8110f-5b82-435a-97f1-eaacb3c51c27")]
            public virtual RepoItemInfo AccessoryPriceInfo
            {
                get
                {
                    return _accessorypriceInfo;
                }
            }

            /// <summary>
            /// The OrderPrice item.
            /// </summary>
            [RepositoryItem("5b8fac29-72de-4b6a-b2c3-4b86768c13ec")]
            public virtual Ranorex.SpanTag OrderPrice
            {
                get
                {
                    return _orderpriceInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The OrderPrice item info.
            /// </summary>
            [RepositoryItemInfo("5b8fac29-72de-4b6a-b2c3-4b86768c13ec")]
            public virtual RepoItemInfo OrderPriceInfo
            {
                get
                {
                    return _orderpriceInfo;
                }
            }

            /// <summary>
            /// The CheckoutButton item.
            /// </summary>
            [RepositoryItem("060068ee-4d52-4fed-9143-38653e3a2e6d")]
            public virtual Ranorex.ButtonTag CheckoutButton
            {
                get
                {
                    return _checkoutbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The CheckoutButton item info.
            /// </summary>
            [RepositoryItemInfo("060068ee-4d52-4fed-9143-38653e3a2e6d")]
            public virtual RepoItemInfo CheckoutButtonInfo
            {
                get
                {
                    return _checkoutbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
