///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RivianR1Configurator
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDemoAppRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c0836b50-6db0-4981-bcd4-46d47038a7f5")]
    public partial class RxDemoAppRepository : RepoGenBaseFolder
    {
        static RxDemoAppRepository instance = new RxDemoAppRepository();
        RxDemoAppRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the RxDemoAppRepository element repository.
        /// </summary>
        [RepositoryFolder("c0836b50-6db0-4981-bcd4-46d47038a7f5")]
        public static RxDemoAppRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDemoAppRepository() 
            : base("RxDemoAppRepository", "/", null, 0, false, "c0836b50-6db0-4981-bcd4-46d47038a7f5", ".\\RepositoryImages\\RxDemoAppRepositoryc0836b50.rximgres")
        {
            _rxmainframe = new RxDemoAppRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c0836b50-6db0-4981-bcd4-46d47038a7f5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("f694972d-0d39-42d4-8e04-20ac1d009621")]
        public virtual RxDemoAppRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxDemoAppRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("f694972d-0d39-42d4-8e04-20ac1d009621")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _txtfirstnameInfo;
            RepoItemInfo _txtlastnameInfo;
            RepoItemInfo _cmbdepartmentInfo;
            RepoItemInfo _updowneditInfo;
            RepoItemInfo _rdbfemaleInfo;
            RepoItemInfo _rdbmaleInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _btndeletepersonInfo;
            RepoItemInfo _michaelscott42managementInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "f694972d-0d39-42d4-8e04-20ac1d009621", "")
            {
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", "", 30000, null, "01d33c48-40de-4c7d-84b5-094a689421ea");
                _txtfirstnameInfo = new RepoItemInfo(this, "TxtFirstName", ".//text[@controlname='txtFirstName']", "", 30000, null, "4aba64eb-c9ce-47a8-8be8-e2b44f17dc83");
                _txtlastnameInfo = new RepoItemInfo(this, "TxtLastName", ".//text[@controlname='txtLastName']", "", 30000, null, "ecca7915-97df-4989-a20f-73bab962a467");
                _cmbdepartmentInfo = new RepoItemInfo(this, "CmbDepartment", ".//combobox[@controlname='cmbDepartment']", "", 30000, null, "73be3d9a-7113-4385-b10e-efcf83f03395");
                _updowneditInfo = new RepoItemInfo(this, "UpDownEdit", ".//text[@controlname='upDownEdit']", "", 30000, null, "62055777-14b4-49ed-89a8-260f2d2dfa8f");
                _rdbfemaleInfo = new RepoItemInfo(this, "RdbFemale", ".//radiobutton[@controlname='rdbFemale']", "", 30000, null, "813ba19b-b94a-4292-a086-42f1ea247321");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", ".//radiobutton[@controlname='rdbMale']", "", 30000, null, "fc3c78d3-f814-44cb-b9b8-0c7932447e63");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", ".//button[@controlname='btnAddPerson']", "", 30000, null, "e9bcedf9-6385-426d-a9b2-1a8106ab77ea");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", ".//button[@controlname='btnDeletePerson']", "", 30000, null, "b621dab1-5572-4f84-b36e-9768c85566ff");
                _michaelscott42managementInfo = new RepoItemInfo(this, "MichaelScott42Management", ".//listitem[1]", "", 30000, null, "7ff5597b-4e94-43ff-be18-3de4b84eb6d0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f694972d-0d39-42d4-8e04-20ac1d009621")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f694972d-0d39-42d4-8e04-20ac1d009621")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("01d33c48-40de-4c7d-84b5-094a689421ea")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("01d33c48-40de-4c7d-84b5-094a689421ea")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The TxtFirstName item.
            /// </summary>
            [RepositoryItem("4aba64eb-c9ce-47a8-8be8-e2b44f17dc83")]
            public virtual Ranorex.Text TxtFirstName
            {
                get
                {
                    return _txtfirstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtFirstName item info.
            /// </summary>
            [RepositoryItemInfo("4aba64eb-c9ce-47a8-8be8-e2b44f17dc83")]
            public virtual RepoItemInfo TxtFirstNameInfo
            {
                get
                {
                    return _txtfirstnameInfo;
                }
            }

            /// <summary>
            /// The TxtLastName item.
            /// </summary>
            [RepositoryItem("ecca7915-97df-4989-a20f-73bab962a467")]
            public virtual Ranorex.Text TxtLastName
            {
                get
                {
                    return _txtlastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtLastName item info.
            /// </summary>
            [RepositoryItemInfo("ecca7915-97df-4989-a20f-73bab962a467")]
            public virtual RepoItemInfo TxtLastNameInfo
            {
                get
                {
                    return _txtlastnameInfo;
                }
            }

            /// <summary>
            /// The CmbDepartment item.
            /// </summary>
            [RepositoryItem("73be3d9a-7113-4385-b10e-efcf83f03395")]
            public virtual Ranorex.ComboBox CmbDepartment
            {
                get
                {
                    return _cmbdepartmentInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The CmbDepartment item info.
            /// </summary>
            [RepositoryItemInfo("73be3d9a-7113-4385-b10e-efcf83f03395")]
            public virtual RepoItemInfo CmbDepartmentInfo
            {
                get
                {
                    return _cmbdepartmentInfo;
                }
            }

            /// <summary>
            /// The UpDownEdit item.
            /// </summary>
            [RepositoryItem("62055777-14b4-49ed-89a8-260f2d2dfa8f")]
            public virtual Ranorex.Text UpDownEdit
            {
                get
                {
                    return _updowneditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The UpDownEdit item info.
            /// </summary>
            [RepositoryItemInfo("62055777-14b4-49ed-89a8-260f2d2dfa8f")]
            public virtual RepoItemInfo UpDownEditInfo
            {
                get
                {
                    return _updowneditInfo;
                }
            }

            /// <summary>
            /// The RdbFemale item.
            /// </summary>
            [RepositoryItem("813ba19b-b94a-4292-a086-42f1ea247321")]
            public virtual Ranorex.RadioButton RdbFemale
            {
                get
                {
                    return _rdbfemaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbFemale item info.
            /// </summary>
            [RepositoryItemInfo("813ba19b-b94a-4292-a086-42f1ea247321")]
            public virtual RepoItemInfo RdbFemaleInfo
            {
                get
                {
                    return _rdbfemaleInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("fc3c78d3-f814-44cb-b9b8-0c7932447e63")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("fc3c78d3-f814-44cb-b9b8-0c7932447e63")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("e9bcedf9-6385-426d-a9b2-1a8106ab77ea")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("e9bcedf9-6385-426d-a9b2-1a8106ab77ea")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("b621dab1-5572-4f84-b36e-9768c85566ff")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("b621dab1-5572-4f84-b36e-9768c85566ff")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }

            /// <summary>
            /// The MichaelScott42Management item.
            /// </summary>
            [RepositoryItem("7ff5597b-4e94-43ff-be18-3de4b84eb6d0")]
            public virtual Ranorex.ListItem MichaelScott42Management
            {
                get
                {
                    return _michaelscott42managementInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The MichaelScott42Management item info.
            /// </summary>
            [RepositoryItemInfo("7ff5597b-4e94-43ff-be18-3de4b84eb6d0")]
            public virtual RepoItemInfo MichaelScott42ManagementInfo
            {
                get
                {
                    return _michaelscott42managementInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
