///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RivianR1Configurator.RxDemoAppAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DataEntry recording.
    /// </summary>
    [TestModule("8f4d936c-2581-4f96-b72d-786e100a38d9", ModuleType.Recording, 1)]
    public partial class DataEntry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RivianR1Configurator.RxDemoAppRepository repository.
        /// </summary>
        public static global::RivianR1Configurator.RxDemoAppRepository repo = global::RivianR1Configurator.RxDemoAppRepository.Instance;

        static DataEntry instance = new DataEntry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DataEntry()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DataEntry Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Michael' on item 'RxMainFrame.TxtFirstName'.", repo.RxMainFrame.TxtFirstNameInfo, new RecordItemIndex(0));
            repo.RxMainFrame.TxtFirstName.Element.SetAttributeValue("Text", "Michael");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Scott' on item 'RxMainFrame.TxtLastName'.", repo.RxMainFrame.TxtLastNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.TxtLastName.Element.SetAttributeValue("Text", "Scott");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute SelectedItemText to 'Management' on item 'RxMainFrame.CmbDepartment'.", repo.RxMainFrame.CmbDepartmentInfo, new RecordItemIndex(2));
            repo.RxMainFrame.CmbDepartment.Element.SetAttributeValue("SelectedItemText", "Management");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '42' on item 'RxMainFrame.UpDownEdit'.", repo.RxMainFrame.UpDownEditInfo, new RecordItemIndex(3));
            repo.RxMainFrame.UpDownEdit.Element.SetAttributeValue("Text", "42");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'RxMainFrame.RdbMale'.", repo.RxMainFrame.RdbMaleInfo, new RecordItemIndex(4));
            repo.RxMainFrame.RdbMale.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'RxMainFrame.BtnAddPerson'.", repo.RxMainFrame.BtnAddPersonInfo, new RecordItemIndex(5));
            repo.RxMainFrame.BtnAddPerson.Press();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'RxMainFrame.MichaelScott42Management'.", repo.RxMainFrame.MichaelScott42ManagementInfo, new RecordItemIndex(6));
            repo.RxMainFrame.MichaelScott42Management.Select();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'RxMainFrame.BtnDeletePerson'.", repo.RxMainFrame.BtnDeletePersonInfo, new RecordItemIndex(7));
            repo.RxMainFrame.BtnDeletePerson.Press();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
